import json
import os
import subprocess
from datetime import datetime

from triage import run_triage
from patcher import generate_patch
from reviewer import review_patch
from github_ops import create_pull_request


def run_cmd(command):
    if isinstance(command, str):
        command = command.split()
    result = subprocess.run(command, shell=False, capture_output=True, text=True)
    print(f"$ {' '.join(command)}")
    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr)
    if result.returncode != 0:
        raise RuntimeError(f"Command failed: {' '.join(command)}")
    return result


def create_branch_name():
    timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    return f"ai-fix-{timestamp}"


def read_file(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        return f.read()


def write_file(file_path, content):
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)


def run_pipeline():
    print("🚀 Starting AI Security Agent...")

    with open("findings.json", "r", encoding="utf-8") as f:
        semgrep_output = json.load(f)

    results = semgrep_output.get("results", [])
    print(f"🔍 Total findings: {len(results)}")

    if not results:
        print("✅ No vulnerabilities found.")
        return

    finding = results[0]
    print("📌 Processing finding:")
    print(json.dumps(finding, indent=2))

    triage = run_triage(finding)
    triage["auto_fix"] = True
    print("🧠 Triage result:")
    print(triage)

    if not triage.get("auto_fix"):
        print("❌ Not eligible for auto-fix")
        return

    file_path = finding["path"]
    original_code = read_file(file_path)

    patch = generate_patch(finding, original_code)
    print("🛠️ Patch generated:")
    print(json.dumps(patch, indent=2))

    review = review_patch(finding, original_code, patch)
    print("🔍 Review result:")
    print(review)

    if not review.get("approved"):
        print("❌ Patch rejected")
        return

    target_file = patch["file_path"]
    fixed_code = patch["fixed_code"]

    write_file(target_file, fixed_code)

    branch_name = create_branch_name()
    run_cmd(["git", "checkout", "-b", branch_name])

    run_cmd(['git', 'config', 'user.name', 'security-agent-bot'])
    run_cmd(['git', 'config', 'user.email', 'security-agent-bot@users.noreply.github.com'])

    run_cmd(["git", "add", target_file])
    run_cmd(['git', 'commit', '-m', 'fix(security): AI-generated remediation'])
    
    token = os.getenv("GH_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY")

    run_cmd(['git', 'remote', 'set-url', 'origin', f'https://x-access-token:{token}@github.com/{repo}.git'])
    run_cmd(["git", "push", "origin", branch_name])

    pr_title = f"fix(security): remediate {finding.get('check_id', 'vulnerability')}"
    pr_body = (
        f"Automated security fix generated by AI.\n\n"
        f"**Summary:** {patch.get('summary', 'No summary')}\n\n"
        f"**Review reason:** {review.get('reason', 'No reason provided')}\n"
    )

    pr = create_pull_request(branch_name, pr_title, pr_body)
    print("✅ Pull request created:")
    print(pr.get("html_url"))


if __name__ == "__main__":
    run_pipeline()